package com.example.demo.utilities;

import java.util.ArrayList;
import java.util.List;

public class MCClist {
	private List<String> res;

	public MCClist() {

	}

	public List<String> getlist() {
		res = new ArrayList<String>();
		res.add("");
		res.add("0742	Veterinary services");
		res.add("0780	Landscaping and horticultural services");
		res.add("4111	Local and suburban commuter passenger transportation, including ferries");
		res.add("4112	Passenger railways");
		res.add("4119	Ambulance services");
		res.add("4121	Taxi-cabs and limousines");
		res.add("4131	Bus lines");
		res.add("4215	Courier services — air and ground and freight forwarders");
		res.add("4411	Steamships and cruise lines");
		res.add("4457	Boat rentals and leasing");
		res.add("4511	Airlines and air carriers");
		res.add("4722	Travel agencies and tour operators");
		res.add("4784	Tolls and bridge fees");
		res.add("4789	Transportation services — not elsewhere classified");
		res.add("4812	Telecommunication equipment and telephone sales");
		res.add("4814	Telecommunication services");
		res.add("4816	Computer network information services");
		res.add("4821	Telegraph services");
		res.add("4899	Cable and other pay television services");
		res.add("4900	Utilities — electric, gas, water and sanitary");
		res.add("5200	Home supply warehouse outlets");
		res.add("5231	Glass, paint and wallpaper shops");
		res.add("5251	Hardware shops");
		res.add("5261	Lawn and garden supplies outlets, including nurseries");
		res.add("5271	Mobile home dealers");
		res.add("5300	Wholesale clubs");
		res.add("5309	Duty-free shops");
		res.add("5310	Discount shops");
		res.add("5311	Department stores");
		res.add("5331	Variety stores");
		res.add("5399	Miscellaneous general merchandise");
		res.add("5411	Groceries and supermarkets");
		res.add("5422	Freezer and locker meat provisioners");
		res.add("5441	Candy, nut and confectionery shops");
		res.add("5451	Dairies");
		res.add("5462	Bakeries");
		res.add("5499	Miscellaneous food shops — convenience and speciality retail outlets");
		res.add("5511	Car and truck dealers (new and used) sales, services, repairs, parts and leasing");
		res.add("5521	Car and truck dealers (used only) sales, service, repairs, parts and leasing");
		res.add("5531	Auto and home supply outlets");
		res.add("5532	Automotive tyre outlets");
		res.add("5533	Automotive parts and accessories outlets");
		res.add("5541	Service stations (with or without ancillary services)");
		res.add("5542	Automated fuel dispensers");
		res.add("5561	Camper, recreational and utility trailer dealers");
		res.add("5571	Motorcycle shops and dealers");
		res.add("5592	Motor home dealers");
		res.add("5598	Snowmobile dealers");
		res.add("5611	Men’s and boys’ clothing and accessory shops");
		res.add("5621	Women’s ready-to-wear shops");
		res.add("5631	Women’s accessory and speciality shops ");
		res.add("5641	Children’s and infants’ wear shops");
		res.add("5651	Family clothing shops");
		res.add("5655	Sports and riding apparel shops");
		res.add("5661	Shoe shops");
		res.add("5681	Furriers and fur shops");
		res.add("5691	Men’s and women’s clothing shops");
		res.add("5697	Tailors, seamstresses, mending and alterations");
		res.add("5698	Wig and toupee shops");
		res.add("5699	Miscellaneous apparel and accessory shops");
		res.add("5712	Furniture, home furnishings and equipment shops and manufacturers, except appliances");
		res.add("5713	Floor covering services");
		res.add("5714	Drapery, window covering and upholstery shops");
		res.add("5718	Fireplaces, fireplace screens and accessories shops");
		res.add("5719	Miscellaneous home furnishing speciality shops");
		res.add("5722	Household appliance shops");
		res.add("5732	Electronics shops");
		res.add("5733	Music shops — musical instruments, pianos and sheet music");
		res.add("5734	Computer software outlets");
		res.add("5735	Record shops");
		res.add("5811	Caterers");
		res.add("5812	Eating places and restaurants");
		res.add("5813	Drinking places (alcoholic beverages) — bars, taverns, night-clubs, cocktail lounges and discothèques");
		res.add("5814	Fast food restaurants");
		res.add("5912	Drug stores and pharmacies");
		res.add("5921	Package shops — beer, wine and liquor");
		res.add("5931	Used merchandise and second-hand shops");
		res.add("5935	Wrecking and salvage yards");
		res.add("5937	Antique reproduction shops");
		res.add("5940	Bicycle shops — sales and service");
		res.add("5941	Sporting goods shops");
		res.add("5942	Bookshops");
		res.add("5943	Stationery, office and school supply shops");
		res.add("5944	Jewellery, watch, clock and silverware shops");
		res.add("5945	Hobby, toy and game shops");
		res.add("5946	Camera and photographic supply shops");
		res.add("5947	Gift, card, novelty and souvenir shops");
		res.add("5948	Luggage and leather goods shops");
		res.add("5949	Sewing, needlework, fabric and piece goods shops");
		res.add("5950	Glassware and crystal shops");
		res.add("5962	Telemarketing — travel-related arrangement services");
		res.add("5963	Door-to-door sales");
		res.add("5964	Direct marketing — catalogue merchants");
		res.add("5965	Direct marketing — combination catalogue and retail merchants");
		res.add("5966	Direct marketing — outbound telemarketing merchants");
		res.add("5967	Direct marketing — inbound telemarketing merchants");
		res.add("5968	Direct marketing — continuity subscription merchants");
		res.add("5969	Direct marketing direct marketers — not elsewhere classified");
		res.add("5970	Artist supply and craft shops");
		res.add("5971	Art dealers and galleries");
		res.add("5972	Stamp and coin shops");
		res.add("5973	Religious goods and shops");
		res.add("5975	Hearing aids — sales, service and supplies");
		res.add("5976	Orthopaedic goods and prosthetic devices");
		res.add("5977	Cosmetic shops");
		res.add("5978	Typewriter outlets — sales, service and rentals");
		res.add("5983	Fuel dealers — fuel oil, wood, coal and liquefied petroleum");
		res.add("5992	Florists");
		res.add("5993	Cigar shops and stands");
		res.add("5994	Newsagents and news-stands");
		res.add("5995	Pet shops, pet food and supplies");
		res.add("5996	Swimming pools — sales, supplies and services");
		res.add("5997	Electric razor shops — sales and service");
		res.add("5998	Tent and awning shops");
		res.add("5999	Miscellaneous and speciality retail outlets");
		res.add("7011	Lodging — hotels, motels and resorts");
		res.add("7032	Sporting and recreational camps");
		res.add("7033	Trailer parks and camp-sites");
		res.add("7210	Laundry, cleaning and garment services");
		res.add("7211	Laundry services — family and commercial");
		res.add("7216	Dry cleaners");
		res.add("7217	Carpet and upholstery cleaning");
		res.add("7221	Photographic studios");
		res.add("7230	Beauty and barber shops");
		res.add("7251	Shoe repair shops, shoe shine parlours and hat cleaning shops");
		res.add("7261	Funeral services and crematoriums");
		res.add("7273	Dating and escort services");
		res.add("7278	Buying and shopping services and clubs");
		res.add("7295	Babysitting and housekeeping services");
		res.add("7296	Clothing rentals — costumes, uniforms and formal wear");
		res.add("7297	Massage parlours");
		res.add("7298	Health and beauty spas");
		res.add("7338	Quick copy, reproduction and blueprinting services");
		res.add("7339	Stenographic and secretarial support services");
		res.add("7342	Exterminating and disinfecting services");
		res.add("7349	Cleaning, maintenance and janitorial services");
		res.add("7393	Detective agencies, protective agencies and security services, including armoured cars and guard dogs");
		res.add("7394	Equipment, tool, furniture and appliance rentals and leasing");
		res.add("7395	Photofinishing laboratories and photo developing");
		res.add("7512	Automobile rentals");
		res.add("7513	Truck and utility trailer rentals");
		res.add("7519	Motor home and recreational vehicle rentals");
		res.add("7523	Parking lots and garages");
		res.add("7531	Automotive body repair shops");
		res.add("7534	Tyre retreading and repair shops");
		res.add("7535	Automotive paint shops");
		res.add("7538	Automotive service shops (non-dealer)");
		res.add("7542	Car washes");
		res.add("7549	Towing services");
		res.add("7622	Electronics repair shops");
		res.add("7623	Air conditioning and refrigeration repair shops");
		res.add("7629	Electrical and small appliance repair shops");
		res.add("7631	Watch, clock and jewellery repair shops");
		res.add("7641	Furniture reupholstery, repair and refinishing");
		res.add("7692	Welding services");
		res.add("7699	Miscellaneous repair shops and related services");
		res.add("7832	Motion picture theatres");
		res.add("7841	Video tape rentals");
		res.add("7911	Dance halls, studios and schools");
		res.add("7922	Theatrical producers (except motion pictures) and ticket agencies");
		res.add("7929	Bands, orchestras and miscellaneous entertainers — not elsewhere classified");
		res.add("7932	Billiard and pool establishments");
		res.add("7933	Bowling alleys");
		res.add("7941	Commercial sports, professional sports clubs, athletic fields and sports promoters");
		res.add("7991	Tourist attractions and exhibits");
		res.add("7992	Public golf courses");
		res.add("7994	Video game arcades and establishments");
		res.add("7996	Amusement parks, circuses, carnivals and fortune tellers");
		res.add("7998	Aquariums, seaquariums and dolphinariums");
		res.add("7999	Recreation services — not elsewhere classified");
		res.add("8011	Doctors and physicians — not elsewhere classified");
		res.add("8021	Dentists and orthodontists");
		res.add("8031	Osteopaths");
		res.add("8041	Chiropractors");
		res.add("8042	Optometrists and ophthalmologists");
		res.add("8043	Opticians, optical goods and eyeglasses");
		res.add("8049	Podiatrists and chiropodists");
		res.add("8050	Nursing and personal care facilities");
		res.add("8062	Hospitals");
		res.add("8071	Medical and dental laboratories");
		res.add("8099	Medical services and health practitioners — not elsewhere classified");
		res.add("8211	Elementary and secondary schools");
		res.add("8220	Colleges, universities, professional schools and junior colleges");
		res.add("8241	Correspondence schools");
		res.add("8244	Business and secretarial schools");
		res.add("8249	Trade and vocational schools");
		res.add("8299	Schools and educational services — not elsewhere classified");
		res.add("8351	Child care services");
		res.add("8675	Automobile associations");
		res.add("8699	Membership organizations — not elsewhere classified");
		return res;
	}
}
